volumes:
  sql:

services:
  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    volumes:
      - ./www/public:/var/www/html:ro
      - ./nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - 80:80

  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./php/conf/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:W7nB7TTGFBB1pdy8/4pUU4E12smKSe2cQ2J7jezan2o=
      APP_DEBUG: true
      APP_URL: http://localhost

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: username
      DB_PASSWORD: password

      BROADCAST_CONNECTION: log

      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: "noreply@test-app.com"
    extra_hosts:
      - host.docker.internal:host-gateway
    user: ${USER_ID}:${GROUP_ID}

  vite:
    image: node:20-alpine3.16
    ports:
      - 5173:5173
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    command: "npm run dev"
    user: ${USER_ID}:${GROUP_ID}

  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - sql:/var/lib/mysql

  mailhog:
    image: cd2team/mailhog
    ports:
      - 81:8025
